{{/*  https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/grafana/configmaps-datasources.yaml*/}}
{{- if and .Values.prometheusOperator.enabled .Values.grafana.enabled .Values.grafana.datasources.enabled }}
{{- $trimmedDashName := include "dash.fullname" . | trunc 43 }}
{{- $dashName := printf "%s-%s" $trimmedDashName "grafana-datasources" | trimSuffix "-" }}
{{- $appName := include "dash.grafana-name" }}
{{- $promName := include "dash.prom-name" . }}
{{- with .Values.grafana -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s" $dashName }}
  {{/*namespace: {{ template "prometheus-operator.namespace" . }}*/}}
  {{- if .datasources.customAnnotations }}
  annotations:
    {{- toYaml .datasources.customAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dash.labels" $ | nindent 6 }}
    {{- if .datasources.includeGrafanaCustomLabels }}
    {{- .customLabels | toYaml | nindent 6 }}
    {{- end }}
    {{- .datasources.customLabels | toYaml | nindent 6 }}
    app: {{ printf "%s" $appName }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      {{- with .datasources }}
      {{- if .defaultPrometheusSource.enabled }}
      - name: Prometheus
        type: prometheus
        {{- if .defaultPrometheusSource.urlOverride }}
        url: {{ .defaultPrometheusSource.urlOverride }}
        {{- else }}
        url: http://{{ printf "%s" $promName }}.{{ $.Release.Namespace }}:{{ $.Values.prometheusOperator.port }}/
        {{- end }}
        access: proxy
        isDefault: true
        jsonData:
          httpMethod: {{ .defaultPrometheusSource.httpMethod }}
          timeInterval: {{ default .defaultScrapeInterval .defaultPrometheusSource.scrapeIntervalOverride }}
      {{- end }}
      {{- .customSources | toJson | nindent 6 }}
      {{- end }}# ends "with .datasources"
{{- end }}

{{- end }}
