{{/*  https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/grafana/configmaps-datasources.yaml*/}}
{{- if and .Values.prometheusOperator.enabled .Values.grafana.enabled .Values.grafana.datasources.enabled }}
{{- $trimmedDashName := include "dash.fullname" . | trunc 43 }}
{{- $appName := printf "%s-%s" $trimmedDashName "grafana-datasources" | trimSuffix "-" }}
{{- with .Values.grafana -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s" $appName }}
  {{/*namespace: {{ template "prometheus-operator.namespace" . }}*/}}
  {{- if .datasources.customAnnotations }}
  annotations:
    {{- toYaml .datasources.customAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dash.labels" $ | nindent 6 }}
    {{- if .datasources.includeGrafanaCustomLabels }}
    {{- .customLabels | toYaml | nindent 6 }}
    {{- end }}
    {{- .datasources.customLabels | toYaml | nindent 6 }}
    app: {{ printf "%s" $appName }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      {{- range .datasources.list }}
      - name: {{ .name }}
        type: {{ .type }}
        url: {{ .url }}
        access: {{ .access }}
        isDefault: {{ .isDefault }}
      {{- end }}
{{- end }}

{{- end }}
