{{/*https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/grafana/servicemonitor.yaml*/}}
{{- if .Values.prometheusOperator.enabled }}
{{- $appName := include "dash.prom-name" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s" $appName }}
  labels:
    {{- include "dash.labels" . | nindent 4 }}
    {{- $.Values.grafana.customLabels | toYaml | nindent 4 }}
    app: {{ printf "%s" $appName }}
spec:
  endpoints:
  - path: /api/v1/metrics
    port: http
  - path: /api/metrics/environment
    port: http
  selector:
    matchLabels:
      {{- include "dash.selectorLabels" . | nindent 6 }}
{{- end }}
