{{/* https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack */}}
{{- if .Values.prometheusOperator.enabled }}
{{- $appName := include "dash.prom-name" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s" $appName }}
  labels:
    {{- include "dash.labels" . | nindent 4 }}
    {{- $.Values.grafana.labels | toYaml | nindent 4 }}
    app: {{ printf "%s" $appName }}
spec:
  endpoints:
  - path: /api/v1/metrics
    port: http
  - path: /api/metrics/environment
    port: http
  selector:
    matchLabels:
      {{- include "dash.selectorLabels" . | nindent 6 }}
{{- end }}
